### ISSUE TITLE
Resolve class names using the Injector API

### ISSUE THREAD

**Issue by Cambis** [Cambis/silverstripe-rector#13]
## Feature request ✨

In Silverstripe you can replace an injectable class using the Injector API, [see here](https://docs.silverstripe.org/en/5/developer_guides/extending/injector/#basic-dependency-injection).

Given that case, we should use the Injector API to resolve the classname of an object incase it has been replaced.

If the service that is being replaced is an interface we should keep the original interface name

#### Replacing an extension

```yml
SilverStripe\Core\Injector\Injector:
  App\Extension\MyExtension:
    class: App\Extension\MyBetterExtension
    
App\Model\MyModel:
  extensions:
    - App\Extension\MyExtension
```

```diff
+ /**
+  * @extends \SilverStripe\Core\Extension<\App\Model\MyModel & static>
+  */
class MyBetterExtension extends \SilverStripe\Core\Extension
{
}
```

#### Registering a service

```yml
SilverStripe\Core\Injector\Injector:
  App\Contract\MyClientInterface:
    class: App\MyClient\MyClient
```

```diff
class MyService
{
  use \SilverStripe\Core\Injector\Injectable;

+  /**
+   * @var \App\Contract\MyClientInterface
+   */
+   public $client
  
  private static array $dependencies = [
    'client' => '%$' . \App\Contract\MyClientInterface::class,
  ];
}
```
